# ──────────────────────────────────────────────────────────────────────────────
# PROMPT 1 — Extract JD params from raw/unstructured JD text
# ──────────────────────────────────────────────────────────────────────────────

JD_EXTRACTION_PROMPT = """
You are a senior recruitment analyst at The Jobs Jungle.
Your task is to extract structured search parameters from a raw job description.

Extract the following and return as valid JSON only:

{{
  "job_title": "exact job title",
  "seniority": "Junior / Mid / Senior / Lead / Principal",
  "must_have": ["skill1", "skill2"],
  "nice_to_have": ["skill1", "skill2"],
  "experience_years": "e.g. 4-6 years",
  "location": "city, country or Remote",
  "domain": "one of: engineering / product_management / data_ai / quality_assurance / devops_cloud / business_gtm",
  "salary_range": "e.g. 25-35 LPA or null if not mentioned",
  "notice_period_days": 30 or null if not mentioned,
  "auto_reject_signals": ["signal1", "signal2"],
  "title_variants": ["variant1", "variant2", "variant3"]
}}

RULES:
- must_have: only hard requirements explicitly stated
- nice_to_have: skills mentioned as preferred/good to have
- auto_reject_signals: treat as SOFT signals not hard filters
- title_variants: 3-4 alternative job titles to widen search
- Return ONLY valid JSON, no explanation, no markdown

JOB DESCRIPTION:
{jd_text}
"""


# ──────────────────────────────────────────────────────────────────────────────
# PROMPT 2 — Extract JD params from structured Stage 1 PDF output
# ──────────────────────────────────────────────────────────────────────────────

STRUCTURED_JD_EXTRACTION_PROMPT = """
You are a senior recruitment analyst at The Jobs Jungle.
You are given a structured intake report generated by the Stage 1 Client Intake Agent.
Extract search parameters for candidate sourcing and return as valid JSON only.

{{
  "job_title": "exact job title from the report",
  "seniority": "Junior / Mid / Senior / Lead / Principal",
  "must_have": ["skill1", "skill2"],
  "nice_to_have": ["skill1", "skill2"],
  "experience_years": "e.g. 4-6 years",
  "location": "city, country or Remote",
  "domain": "one of: engineering / product_management / data_ai / quality_assurance / devops_cloud / business_gtm",
  "salary_range": "e.g. 25-35 LPA or null if not mentioned",
  "notice_period_days": 30 or null if not mentioned,
  "auto_reject_signals": ["signal1", "signal2"],
  "title_variants": ["variant1", "variant2", "variant3"]
}}

RULES:
- Pull must_have directly from "Must Have Requirements" section
- Pull nice_to_have from "Nice To Have Requirements" section
- auto_reject_signals: use "Auto Reject Criteria" section as SOFT signals
- title_variants: generate 3-4 alternative job titles to widen search
- Return ONLY valid JSON, no explanation, no markdown

INTAKE REPORT:
{jd_text}
"""


# ──────────────────────────────────────────────────────────────────────────────
# PROMPT 3 — Build Tavily search queries from JD params
# ──────────────────────────────────────────────────────────────────────────────

SEARCH_QUERY_PROMPT = """
You are a recruitment sourcing specialist.
Generate 3 simple natural language search queries to find candidate LinkedIn profiles.

JD Parameters:
- Job Title: {job_title}
- Title Variants: {title_variants}
- Must Have Skills: {must_have}
- Seniority: {seniority}
- Experience: {experience_years}
- Location: {location}

CRITICAL RULES:
- Queries must be SHORT and SIMPLE — like a Google search a human would type
- NO boolean operators (no AND, OR, NOT, parentheses)
- Each query must end with: site:linkedin.com/in
- Each query uses different skill combinations for variety
- Location: if "Remote" use "India" as location fallback for broader results

Example of CORRECT format:
[
  "Senior Python FastAPI Engineer Bangalore site:linkedin.com/in",
  "Backend Engineer AWS AI LLM experience India site:linkedin.com/in",
  "Senior Software Engineer Python cloud microservices site:linkedin.com/in"
]

Example of WRONG format (never do this):
[
  "(Senior Backend Engineer OR AI Engineer) AND (Python AND FastAPI) AND site:linkedin.com/in"
]

Return ONLY a JSON array of exactly 3 short simple query strings.
No explanation, no markdown, just the JSON array.
"""


# ──────────────────────────────────────────────────────────────────────────────
# PROMPT 4 — Extract candidate profiles from Tavily search results
# ──────────────────────────────────────────────────────────────────────────────

CANDIDATE_EXTRACTION_PROMPT = """
You are a recruitment data extraction specialist at The Jobs Jungle.
Extract candidate profiles from these web search results.

For each result that represents a real person's LinkedIn profile, extract:
{{
  "name": "full name or null if not identifiable",
  "title": "current job title",
  "company": "current company",
  "location": "city, country",
  "linkedin_url": "full LinkedIn URL",
  "skills": ["skill1", "skill2"],
  "experience": "years of experience if mentioned, else null"
}}

RULES:
- Skip results that are job postings, articles, or company pages
- Skip results where name cannot be identified
- Extract only real person profiles
- skills: extract from title and snippet only what is explicitly mentioned
- Return ONLY a JSON array of candidate objects
- If no valid profiles found, return empty array []

SEARCH RESULTS:
{search_results}
"""


# ──────────────────────────────────────────────────────────────────────────────
# PROMPT 5 — AI re-ranking of candidates against JD
# ──────────────────────────────────────────────────────────────────────────────

RERANKING_PROMPT = """
You are a senior technical recruiter at The Jobs Jungle.
Score and rank these candidates against the job requirements.

JOB REQUIREMENTS:
- Title: {job_title}
- Seniority: {seniority}
- Must Have: {must_have}
- Nice To Have: {nice_to_have}
- Experience: {experience_years}
- Location: {location}
- Auto Reject Signals (SOFT — flag only, do not eliminate): {auto_reject_signals}

CANDIDATES:
{candidates}

For each candidate return:
{{
  "id": "candidate id",
  "match_score": 0-100 integer,
  "match_reason": "1-2 sentence specific reason citing actual skills/experience",
  "soft_flags": [
    {{"field": "field_name", "message": "specific flag message"}}
  ],
  "availability_signal": "open_to_work" | "recently_left" | "freelancing" | "none",
  "availability_note": "short note explaining the signal or null if none",
  "career_trajectory": "ascending" | "stable" | "unclear",
  "startup_fit": true | false
}}

SCORING RULES:
- 85-100: Meets all must-have, strong seniority match, right location
- 70-84:  Meets most must-have, minor gaps
- 50-69:  Meets some must-have, notable gaps
- Below 50: Weak match — include but rank low
- NEVER eliminate based on auto_reject_signals — flag them as soft_flags instead
- match_reason MUST cite specific skills from their profile, never generic statements
- soft_flags only when auto_reject signal is detected on that candidate

AVAILABILITY SIGNAL RULES — detect from title, company and snippet:
- "open_to_work": headline/bio contains "open to work", "seeking", "looking for opportunities"
- "recently_left": title starts with "Ex-", "Former", "Previously at", or company is blank/unknown
- "freelancing": title contains "Freelance", "Consultant", "Independent", "Contract"
- "none": no availability signal detected

CAREER TRAJECTORY RULES:
- "ascending": progressive titles visible (Dev → Senior → Lead) or growing responsibilities
- "stable": same level across roles, consistent domain
- "unclear": not enough info to determine

STARTUP FIT RULES:
- true: has startup/early-stage company experience, or title mentions ownership/founding/0-to-1
- false: only large enterprise background

Return ONLY a JSON array of scoring objects, one per candidate.
Preserve original candidate id values exactly.
"""